### ISSUE TITLE
Fn::Invoke crashes Pulumi

### ISSUE THREAD

**Issue by BoSoeborgPetersen** [pulumi/pulumi-yaml#215]
### What happened?

I just wanted to get the current subscription id for Azure to avoid hardcoding it.
So I tried to get the config with:
azure-native:authorization:getClientConfig
And then I wanted to do:
${config.subscriptionId}

### Steps to reproduce

```
  config:
    Fn::Invoke:
      Function: azure-native:authorization:getClientConfig
      Arguments: {}

```
### Expected Behavior

Azure-native configuration retrieved

### Actual Behavior

```
Previewing update (Test)

View Live: https://app.pulumi.com/Bo_Petersen/github-actions-runners-cluster/Test/previews/6e7e7b0d-723d-4413-9049-2babae46ebae

     Type                 Name                                 Plan     Info
     pulumi:pulumi:Stack  github-actions-runners-cluster-Test           1 error; 39 messages
 @v
Diagnostics:
  pulumi:pulumi:Stack (github-actions-runners-cluster-Test):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x30 pc=0x17cc1c6]
    goroutine 26 [running]:
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.resourcePackage.FunctionTypeHint({0x1bc0f50}, {0xc01b0ed1d0, 0xc000034690})  
        /Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/packages.go:395 +0x66
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*typeCache).typeInvoke(0xc0004b4cb0, 0xc0366ddb80, 0xc0000239c0)
        /Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:70 +0x90
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*typeCache).typeExpr(...)
        /Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:102
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.walker.walk({0x0, 0x0, 0x0, 0xc0004b4cc0, 0xc0004b4cd0}, 0xc000126b18, {0x1bbefe8, 0xc0000239c0})
        /Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:139 +0x8c
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.walker.EvalVariable({0x0, 0x0, 0x0, 0xc0004b4cc0, 0xc0004b4cd0}, 0xc00004c200, {{{0x1bb0c60, 0xc00001d7e0}, 0xc00001d600, {0x1bbf3a8, ...}}, ...})
        /Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:205 +0x20b
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*runner).Run(0xc00004c200, {0x1bcb268, 0xc0008ebb30})
        /Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/run.go:510 +0x4fe
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.TypeCheck(0xc0000d34f0)
        /Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/analyser.go:119 +0x12d
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.RunTemplate(0xc000126a00, 0xc000448680, {0x1bc0f50, 0xc0004a02e0})
        /Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/run.go:180 +0x16f
    github.com/pulumi/pulumi-yaml/pkg/server.(*yamlLanguageHost).Run.func1(0x1a13b00)
        /Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/server/server.go:155 +0xb1
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc000126a00, 0xc0000d3858)
        /Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.31.0/go/pulumi/run.go:103 +0x199
    github.com/pulumi/pulumi-yaml/pkg/server.(*yamlLanguageHost).Run(0xc0008d67c0, {0x1bca9a8, 0xc000160030}, 0xc0006d66c0)   
        /Users/runner/work/pulumi-yaml/pulumi-yaml/pkg/server/server.go:147 +0x42c
    github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_Run_Handler.func1({0x1bca9a8, 0xc000160030}, {0x19ddca0, 0xc0006d66c0})
        /Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.31.0/proto/go/language.pb.go:594 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1bca9a8, 0xc0000a3a70}, {0x19ddca0, 0xc0006d66c0}, 0xc000120540, 0xc000117668)
        /Users/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x406
    github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_Run_Handler({0x1932520, 0xc0008d67c0}, {0x1bca9a8, 0xc0000a3a70}, 0xc0001591a0, 0xc0008bf840)
        /Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.31.0/proto/go/language.pb.go:596 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006d0c40, {0x1bdd0b8, 0xc000718d00}, 0xc000180360, 0xc000046150, 0x230e5f8, 0x0)
        /Users/runner/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
    google.golang.org/grpc.(*Server).handleStream(0xc0006d0c40, {0x1bdd0b8, 0xc000718d00}, 0xc000180360, 0x0)
        /Users/runner/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /Users/runner/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/runner/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:919 +0x294

    error: error reading from server: read tcp 127.0.0.1:65342->127.0.0.1:65341: wsarecv: An existing connection was forcibly 
closed by the remote host.


warning: A new version of Pulumi is available. To upgrade from version '3.32.1' to '3.33.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Versions used

```
CLI
Version      3.32.1
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  unknown
kubernetes    unknown
yaml          unknown

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19044 Build 19044
Arch     x86_64

Current Stack: Test

TYPE                                          URN
pulumi:pulumi:Stack                           urn:pulumi:Test::github-actions-runners-cluster::pulumi:pulumi:Stack::github-actions-runners-cluster-Test
pulumi:providers:azure-native                 urn:pulumi:Test::github-actions-runners-cluster::pulumi:providers:azure-native::default
azure-native:resources:ResourceGroup          urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup::resourceGroup
azure-native:operationalinsights:Workspace    urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup$azure-native:operationalinsights:Workspace::workspace
azure-native:containerregistry:Registry       urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup$azure-native:containerregistry:Registry::registry
azure-native:containerservice:ManagedCluster  urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup$azure-native:containerservice:ManagedCluster::managedCluster
azure-native:authorization:RoleAssignment     urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup$azure-native:containerservice:ManagedCluster$azure-native:authorization:RoleAssignment::roleAssignment
pulumi:providers:kubernetes                   urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup$azure-native:containerservice:ManagedCluster$pulumi:providers:kubernetes::kubernetes
kubernetes:core/v1:Namespace                  urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup$azure-native:containerservice:ManagedCluster$kubernetes:core/v1:Namespace::certManagerNamespace
kubernetes:core/v1:Namespace                  urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup$azure-native:containerservice:ManagedCluster$kubernetes:core/v1:Namespace::githubArcNamespace
kubernetes:core/v1:Namespace                  urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup$azure-native:containerservice:ManagedCluster$kubernetes:core/v1:Namespace::kuredNamespace
kubernetes:helm.sh/v3:Release                 urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup$azure-native:containerservice:ManagedCluster$kubernetes:helm.sh/v3:Release::certManager
kubernetes:helm.sh/v3:Release                 urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup$azure-native:containerservice:ManagedCluster$kubernetes:core/v1:Namespace$kubernetes:helm.sh/v3:Release::kured
kubernetes:helm.sh/v3:Release                 urn:pulumi:Test::github-actions-runners-cluster::azure-native:resources:ResourceGroup$azure-native:containerservice:ManagedCluster$kubernetes:core/v1:Namespace$kubernetes:helm.sh/v3:Release::githubArc      


Found no pending operations associated with Test

Backend
Name           pulumi.com
URL            https://app.pulumi.com/Bo_Petersen
User           Bo_Petersen
Organizations  Bo_Petersen

Pulumi locates its logs in C:\Users\BOSOBO~1\AppData\Local\Temp by default
warning: Failed to get information about the project runtime: Unknown Language: yaml: %!!(MISSING)w(<nil>)
warning: Failed to get information about the Pulumi program's plugins: Unknown Language: yaml
warning: A new version of Pulumi is available. To upgrade from version '3.32.1' to '3.33.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@BoSoeborgPetersen thank you for providing a minimized example.
